version: '3.1'
services:
  database:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: supersecretpassword
    networks:
      - backend_api

  api:
    build:
      dockerfile: infrastructure/docker/Dockerfile
      context: .
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - database
    networks:
      - backend_api

networks:
  backend_api:
    driver: bridge
