version: '3.8'
services:
  database:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: supersecretpassword
    networks:
      - backend_api

  api:
    build:
      dockerfile: infrastructure/docker/Dockerfile
      context: .
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      DB_DRIVER: "postgresql"
      DB_USER: "user"
      DB_PASSWORD: "supersecretpassword"
      DB_HOST: "database"
      DB_PORT: 5432
    depends_on:
      - database
    networks:
      - backend_api
    links:
      - database

networks:
  backend_api:
    driver: bridge
