version: '3.1'
services:
  database:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: supersecretpassword
  api:
    build: .
    volumes:
      - ../../.:/app
    ports:
      - "8000:8000"
    depends_on:
      - database
